In [1]:
import cv2
import matplotlib.pyplot as plt
from skimage.feature import hog
from skimage import data, color, exposure
import numpy as np
import os

In [2]:
def getHOGDescriptor(imagePath):
    im = cv2.imread(imagePath)
    gr = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY) 
    gr1 = cv2.resize(gr,(64*2,64*2))

    fd, hog_image = hog(gr1, orientations=9, pixels_per_cell=(4, 4),
                    cells_per_block=(1, 1), visualise=True)
    return fd

In [50]:
target = [] 
HOG_DESC = []
path = '/home/spratik/OCR_HOG/positive_image'
for root ,dir , file in os.walk(path):
    #print root
    dirName = root.split('/')
    count = 0
    for name in file:
       #print name
       imagePath = os.path.join(root,name)
       dec = getHOGDescriptor(imagePath)
       HOG_DESC.append(dec)
       #print imagePath
       count += 1
    num = dirName.pop() 
    #print "dirName: " + num + "--> count:" + str(count)
    for n in range(count): 
        target.append(int(num)) 
        
print target     
print HOG_DESC        

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[array([ 0.02827287,  0.158555

In [54]:
hog_des = np.array(HOG_DESC)
print hog_des

[[ 0.02827287  0.15855592  0.130658   ...,  0.          0.09829097
   0.11543689]
 [ 0.1566459   0.0248247   0.05900764 ...,  0.06538927  0.04715287  0.        ]
 [ 0.31614384  0.06426538  0.08128998 ...,  0.          0.          0.04049411]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.06414754]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]]


In [55]:
print hog_des.shape

(323, 9216)


In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(hog_des, target,test_size = 0.30,random_state=0)

In [58]:
x_train.shape

(226, 9216)

In [59]:
x_test

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.18149697,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.04229885,  0.        ,  0.0598196 , ...,  0.        ,
         0.        ,  0.        ]])

In [60]:
y_train

[3,
 6,
 3,
 1,
 9,
 2,
 5,
 7,
 6,
 8,
 0,
 8,
 3,
 6,
 9,
 9,
 3,
 4,
 0,
 0,
 4,
 5,
 2,
 7,
 1,
 7,
 3,
 9,
 4,
 3,
 0,
 5,
 8,
 0,
 9,
 4,
 7,
 3,
 4,
 2,
 3,
 1,
 1,
 5,
 6,
 0,
 6,
 4,
 1,
 4,
 7,
 5,
 0,
 7,
 4,
 9,
 2,
 1,
 7,
 0,
 3,
 9,
 2,
 1,
 3,
 8,
 8,
 9,
 5,
 4,
 6,
 0,
 8,
 4,
 2,
 7,
 4,
 2,
 3,
 7,
 2,
 2,
 1,
 0,
 4,
 3,
 2,
 6,
 0,
 5,
 6,
 1,
 8,
 2,
 2,
 7,
 3,
 1,
 2,
 4,
 0,
 8,
 8,
 2,
 5,
 8,
 4,
 0,
 6,
 0,
 7,
 4,
 8,
 0,
 6,
 9,
 5,
 4,
 3,
 4,
 8,
 7,
 9,
 4,
 6,
 3,
 9,
 7,
 3,
 6,
 1,
 6,
 1,
 6,
 5,
 2,
 5,
 7,
 2,
 1,
 0,
 1,
 0,
 6,
 5,
 8,
 8,
 8,
 1,
 0,
 9,
 3,
 2,
 5,
 4,
 9,
 9,
 1,
 4,
 5,
 9,
 6,
 0,
 3,
 1,
 7,
 6,
 0,
 1,
 1,
 7,
 8,
 4,
 0,
 8,
 7,
 6,
 6,
 8,
 8,
 6,
 9,
 2,
 5,
 5,
 9,
 4,
 3,
 2,
 2,
 9,
 5,
 0,
 6,
 0,
 9,
 6,
 0,
 5,
 7,
 3,
 4,
 7,
 6,
 1,
 2,
 5,
 0,
 5,
 0,
 8,
 3,
 1,
 1,
 1,
 0,
 4,
 6,
 3,
 2,
 3,
 4,
 3,
 7,
 8,
 5]

In [61]:
y_test


[0,
 8,
 2,
 6,
 9,
 9,
 7,
 4,
 8,
 5,
 5,
 5,
 1,
 3,
 3,
 8,
 2,
 4,
 1,
 7,
 3,
 8,
 5,
 3,
 1,
 5,
 5,
 0,
 2,
 2,
 3,
 6,
 2,
 5,
 2,
 6,
 8,
 2,
 7,
 7,
 7,
 5,
 9,
 8,
 9,
 9,
 9,
 4,
 3,
 5,
 0,
 6,
 8,
 8,
 8,
 9,
 4,
 8,
 6,
 4,
 2,
 2,
 1,
 2,
 3,
 5,
 4,
 3,
 3,
 2,
 2,
 0,
 2,
 4,
 9,
 1,
 5,
 8,
 7,
 3,
 7,
 4,
 4,
 6,
 5,
 4,
 6,
 9,
 1,
 0,
 0,
 6,
 7,
 2,
 3,
 2,
 8]

In [62]:
from sklearn import svm
#clf = SVC(kernel='rbf',random_state=33)
clf = svm.NuSVC(random_state=33)
clf.fit(x_train, y_train)

NuSVC(cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
   max_iter=-1, nu=0.5, probability=False, random_state=33, shrinking=True,
   tol=0.001, verbose=False)

In [63]:
clf.score(x_test,y_test)

0.865979381443299

In [64]:
y_p = clf.predict(x_test)

In [65]:
from sklearn.metrics import confusion_matrix

In [66]:
confusion_matrix(y_test, y_p)

array([[ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  3,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  6,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0, 11,  0],
       [ 1,  0,  1,  1,  0,  0,  0,  0,  1,  5]])

In [69]:
np.array(y_test)

array([0, 8, 2, 6, 9, 9, 7, 4, 8, 5, 5, 5, 1, 3, 3, 8, 2, 4, 1, 7, 3, 8, 5,
       3, 1, 5, 5, 0, 2, 2, 3, 6, 2, 5, 2, 6, 8, 2, 7, 7, 7, 5, 9, 8, 9, 9,
       9, 4, 3, 5, 0, 6, 8, 8, 8, 9, 4, 8, 6, 4, 2, 2, 1, 2, 3, 5, 4, 3, 3,
       2, 2, 0, 2, 4, 9, 1, 5, 8, 7, 3, 7, 4, 4, 6, 5, 4, 6, 9, 1, 0, 0, 6,
       7, 2, 3, 2, 8])

In [68]:
y_p

array([0, 8, 2, 4, 9, 9, 7, 4, 8, 5, 5, 5, 3, 3, 3, 8, 2, 4, 1, 7, 8, 8, 5,
       3, 1, 5, 5, 0, 2, 2, 3, 6, 2, 5, 3, 6, 8, 2, 7, 7, 7, 5, 0, 8, 3, 9,
       9, 4, 3, 5, 0, 6, 8, 8, 8, 8, 4, 8, 6, 4, 3, 2, 1, 2, 3, 5, 4, 3, 3,
       3, 2, 0, 2, 4, 9, 1, 5, 3, 7, 8, 7, 4, 4, 6, 5, 4, 6, 2, 1, 0, 0, 8,
       7, 2, 3, 2, 8])